# Generated by Django 2.2.6 on 2019-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20191102_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
